version: '3.8'

services:
  web:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./capturemate_app:/app
    environment:
      - DB_URI=mongodb://mongodb:27017
      - PYTHONUNBUFFERED=1
      - DEBUG=1
    depends_on:
      - mongodb
    command: python manage.py runserver 0.0.0.0:3001

  # frontend:
  #   build: 
  #     context: ./CaptureMate-frontend-main
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   environment:
  #     - VITE_API_URL=http://localhost:3001
  #   depends_on:
  #     - web

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: